#!/bin/bash
ULAFFDIR="$(dirname "$(readlink -f "${0}")")"
cd $ULAFF_DIR
export PYTHONPATH=$ULAFF_DIR/lib
$ULAFF_DIR/software/bin/python $ULAFF_DIR/software/bin/ipython notebook --no-browser --ip=0.0.0.0 --ipython-dir=$ULAFF_DIR/software/.ipython
