VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "precise32.box"
  config.vm.provision :shell, :path => "postinstall.sh"
end
